spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  datasource:
    url: jdbc:h2:mem:maindb

  h2:
    console:
      enabled: true
      path: /h2-console
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
