spring:
  data:
    mongodb:
      host: localHost
      port: 0 # when flapdoodle using
      database: libraryMongo
  shell:
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongodb.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local