spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
  application:
    name: my-music
  docker:
    compose:
      file: ./project/docker/docker-compose.yml
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: false
jwt:
  token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      base64: true
      expiration-ttl: PT24H
      header: Authorization
  bearer-prefix: "Bearer "